language: node_js
matrix:
  include:
    # Currently supported Node.js releases: https://nodejs.org/en/about/releases/
    - node_js: 10
    - node_js: 12
    - node_js: lts/* # latest LTS release
    - node_js: node # latest stable release
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - export EDGE_PATH="$(pwd)/edge-linux/edge"
  - yarn build
script:
  - yarn test-formatting
  - yarn type-check
  - yarn test
addons:
  edge: stable
services:
  - xvfb
